#!/bin/bash
set -e

echo "CPU FAN PWM controlled depending on CPU temperature"

PWM_FAN='/sys/class/pwm/pwmchip1'

TEMP_MAX=70  # above this temperature the CPU FAN runs at full duty cycle (max speed)
             # in between 65 and 70 degrees Celsius the CPU FAN runs with default duty cycle
TEMP_STOP=65 # lower limit temperature at which the CPU FAN stops

if [ ! -d /sys/class/pwm/pwmchip1/pwm0 ]; then
    echo 0 > ${PWM_FAN}/export;
fi

while [ 1 ]
do

	TEMP=$(sed 's/000$//g'  < /sys/class/thermal/thermal_zone0/temp)

	if [ ${TEMP} -le ${TEMP_STOP} ]; then
		if [ -d "${PWM_FAN}/pwm0" ]; then
			echo 0 > ${PWM_FAN}/pwm0/duty_cycle
			echo 1 > ${PWM_FAN}/pwm0/period
			echo 0 > ${PWM_FAN}/pwm0/enable
		fi
	fi

	if [ ${TEMP} -gt ${TEMP_STOP} ] && [ ${TEMP} -le ${TEMP_MAX} ]; then
		if [ -d "${PWM_FAN}/pwm0" ]; then
			echo 45000 > ${PWM_FAN}/pwm0/period
			echo 18000 > ${PWM_FAN}/pwm0/duty_cycle
			echo 1 > ${PWM_FAN}/pwm0/enable
		fi
	fi

	if [ ${TEMP} -gt ${TEMP_MAX} ]; then
		if [ -d "${PWM_FAN}/pwm0" ]; then
			echo 45000 > ${PWM_FAN}/pwm0/period
			echo 45000 > ${PWM_FAN}/pwm0/duty_cycle
			echo 1 > ${PWM_FAN}/pwm0/enable
		fi
	fi

	sleep 1

done

exit 0
