#!/bin/bash
set -e

echo "CPU FAN PWM controlled depending on CPU temperature"

GV='/sys/devices/system/cpu/cpu0/cpufreq'
PWM_FAN='/sys/class/pwm/pwmchip1/'
echo userspace > ${GV}/scaling_governor
LIMIT=65

echo 0 > ${PWM_FAN}/export

while [ 1 ]
do
    TEMP=$(sed 's/000$//g'  < /sys/class/thermal/thermal_zone0/temp)
    if [[ ${TEMP} -gt ${LIMIT} ]]
    then
	if [ -d "${PWM_FAN}/pwm0" ]; then
		echo 45000 > ${PWM_FAN}/pwm0/period
		echo 45000 > ${PWM_FAN}/pwm0/duty_cycle
		echo 1 > ${PWM_FAN}/pwm0/enable
	fi
    else
	if [ -d "${PWM_FAN}/pwm0" ]; then
		echo 45000 > ${PWM_FAN}/pwm0/period
		echo 6000 > ${PWM_FAN}/pwm0/duty_cycle
		echo 1 > ${PWM_FAN}/pwm0/enable
	fi
    fi
    sleep 1
done

exit 0
