#!/bin/sh

set -e

#gpio4_io5 - tft_stby
if [ ! -d /sys/class/gpio/gpio101 ]
then
  echo 101 > /sys/class/gpio/export
  # Short delay while GPIO permissions are set up
  sleep 1;
fi

echo out > /sys/class/gpio/gpio101/direction
echo 1 > /sys/class/gpio/gpio101/value

sleep 0.2

#gpio5_io18 - tft_bcl_pwm
if [ ! -d /sys/class/gpio/gpio146 ]
then
  echo 146 > /sys/class/gpio/export
  # Short delay while GPIO permissions are set up
  sleep 1;
fi

echo out > /sys/class/gpio/gpio146/direction
echo 0 > /sys/class/gpio/gpio146/value

sleep 0.2

#gpio4_io1 - tft_shlr
if [ ! -d /sys/class/gpio/gpio97 ]
then
  echo 97 > /sys/class/gpio/export
  # Short delay while GPIO permissions are set up
  sleep 1;
fi

echo out > /sys/class/gpio/gpio97/direction
echo 0 > /sys/class/gpio/gpio97/value

sleep 0.2

#gpio4_io16 -tft_updw
if [ ! -d /sys/class/gpio/gpio112 ]
then
  echo 112 > /sys/class/gpio/export
  # Short delay while GPIO permissions are set up
  sleep 1;
fi

echo out > /sys/class/gpio/gpio112/direction
echo 1 > /sys/class/gpio/gpio112/value

sleep 0.2

#gpio3_io25 - tft_rst
if [ ! -d /sys/class/gpio/gpio89 ]
then
  echo 89 > /sys/class/gpio/export
  # Short delay while GPIO permissions are set up
  sleep 1;
fi

echo out > /sys/class/gpio/gpio89/direction
echo 1 > /sys/class/gpio/gpio89/value

exit 0
