#!/bin/sh

set -e

if [ -d /sys/class/pwm/pwmchip2 ]
then
  echo 0 > /sys/class/pwm/pwmchip2/export
  # Short delay
  sleep 1;

  if [ -d /sys/class/pwm/pwmchip2/pwm0 ]
  then
    echo 45000 > /sys/class/pwm/pwmchip2/pwm0/period
    echo 45000 > /sys/class/pwm/pwmchip2/pwm0/duty_cycle
    echo 1 > /sys/class/pwm/pwmchip2/pwm0/enable
  fi
fi

exit 0